### PR TITLE
parse-string added

### PR DESCRIPTION
**Pull request by kokosro**
I had to create a second pull, as my squash of previous commits has become a mess. Thank you

### CODE REVIEW

**Comment by weavejester** [comment]
I've just noticed that `parse-string` doesn't have a test. Could you add one in?

**Comment by kokosro** [comment]
I have added a test for parse-string and merged all commits into one

**Comment by weavejester** [comment]
Oh, you don't need to add so many tests! Just a single line will do. Otherwise we're just testing the parsing twice; once in test-parse, and again in test-parse-string,

**Comment by kokosro** [comment]
I have removed the unnecessary tests. Thank you.

**Pull request merged**
