### PR TITLE
Update the jsoup and clojure versions

### PR DESCRIPTION
**Pull request by dakrone**
Jsoup has had a lot of improvements since version 1.6.2, this tiny change just bumps the jsoup version to 1.7.1 and the clojure version to 1.4.0.

### CODE REVIEW

**Comment by weavejester** [comment]
What's the reason for updating the minimum Clojure version to 1.4.0?

**Comment by dakrone** [comment]
This isn't hard-coded, crouton can still be used with Clojure 1.2/1.3/1.4/1.5. This just changes the default for development to 1.4 since it's the latest stable release.

**Comment by dakrone** [comment]
Alternatively, if you want to switch to lein2 for the project (I felt that was a separate change and didn't want to make that for this pull request), you could do:

``` clojure
(defproject crouton "0.1.0"
  :description "A HTML parsing library"
  :url "https://github.com/weavejester/crouton"
  :license {:name "Eclipse Public License"
  :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.jsoup/jsoup "1.7.1"]]
  :profiles {:dev {:dependencies [[org.clojure/clojure "1.4.0"]]}})
```

Which is technically more correct, because it declares no dependency on clojure at all except for development (since crouton is a library, not an application).

**Comment by weavejester** [comment]
Removing the Clojure dependency entirely indicates that the library doesn't make use of Clojure's core functions, which is incorrect, because it does.

And if you're going to have a Clojure version, the most sensible version to choose is the minimum compatible version. That guards against accidental use of syntax or functions that would make the library incompatible with previous versions of Clojure.

Now, granted I could use:

``` clojure
:dependencies [[org.clojure/clojure "1.4.0"]
               [org.jsoup/jsoup "1.7.1"]]
:profiles {:dev {:dependencies [[org.clojure/clojure "1.3.0"]]}}
```

But that seems unnecessarily verbose, and it removes a useful hint for end users as to the minimum version of Clojure they can use. The best solution is therefore:

``` clojure
:dependencies [[org.clojure/clojure "1.3.0"]
               [org.jsoup/jsoup "1.7.1"]]
```

**Comment by dakrone** [comment]
Okay, I think we disagree on the project layout, but I'm fine with either solution you would like to do as long as it includes bumping the jsoup version to 1.7.1 and releasing a new version of Crouton.

Would you like me to change the pull request to be the same, but with version 1.3.0?

**Comment by weavejester** [comment]
Sure. Either than or rebase the current pull request branch.

**Comment by dakrone** [comment]
@weavejester okay, bumped it back down to 1.3.0.

**Comment by weavejester** [comment]
Could you squash the commits?

**Comment by dakrone** [comment]
Squashed into a single commit updating the Jsoup version.

**Comment by dakrone** [comment]
@weavejester could you make a release with this change please?

**Comment by weavejester** [comment]
@dakrone 0.1.1 has been released. Sorry about the delay.

**Pull request merged**
